### ISSUE TITLE
Crash with Node.js v16

### ISSUE THREAD

**Issue by eagletmt** [bdash-app/bdash-server#21] opened 2022-02-26 18:03 UTC
I could not sign in local bdash-server with Node.js v16 (or v17) because of crash. bdash-server with Node.js v14 works well.
Node.js v14 is still maintained over a year but the current active LTS is v16.
https://nodejs.org/en/about/releases/

```
% node --version
v16.13.2
% yarn dev
```

Opening http://localhost:3000 and proceed login or sending a valid session cookie causes Node.js crash.

```
% curl 'http://localhost:3000/api/users/queries/getCurrentUser' -X POST -H 'Content-Type: application/json' -H 'Cookie: bdash-server_sSessionToken=*REDACTED*' -d '{"params":null,"meta":{}}'
```

```
/usr/bin/node[29161]: ../src/node_http_parser.cc:567:static void node::{anonymous}::Parser::Initialize(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[3]->IsInt32()' failed.
 1: 0x55e263debd25 node::Abort() [/usr/bin/node]
 2: 0x55e263dec074 node::Assert(node::AssertionInfo const&) [/usr/bin/node]
 3: 0x55e263e07a75  [/usr/bin/node]
 4: 0x55e26403b6e8 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/bin/node]
 5: 0x55e26403beb2  [/usr/bin/node]
 6: 0x55e26403c332 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]
 7: 0x55e26486eb19  [/usr/bin/node]
```

**Comment by morishin** [comment] 2022-03-08 04:11
Fixed by #22 ✅ 

The cause of this problem is probably https://github.com/prisma/prisma/issues/6682 .

**Closed as completed by morishin** 2022-03-08 04:11 UTC
